### PR TITLE
Added empty 2D unity game.

### PR DESCRIPTION
**Pull request by JackDevMats**

### CODE REVIEW

**Comment by kiblitz** [comment]
Any reason we have a `furious-fragments` subfolder?

**Comment by JackDevMats** [comment]
i wanted to segment unity engine data from everything else, but maybe  thats not necessary?

**Comment by kiblitz** [comment]
I think we should remove the subfolder. I think having README/LICENSE in the same folder should be fine

**Comment by JackDevMats** [comment]
moved files out of sub directory started new pr

**Pull request closed without merging**
